### ISSUE TITLE
qemu-android-x86 is not working (Invalid url)

### ISSUE THREAD

**Issue by EldoDebug** [refutationalist/saur#10]
It does not work correctly because osdn.net is not running
It need to change to this url and update it
https://downloads.sourceforge.net/project/android-x86/Release%209.0/android-x86_64-9.0-r2.iso?ts=gAAAAABl63bYQJ2TRtIjnhUauCbKbe3zsin5u0yaUnTCM0y4ykJT0lX4i-o4PYOqc65qL8bIAvwQdD_FpinDhCegBobForDplA%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fandroid-x86%2Ffiles%2Flatest%2Fdownload

From the aur form Not_Available comment
https://aur.archlinux.org/packages/qemu-android-x86

**Comment by refutationalist** [comment]
I've upgraded the PKGBUILD to grab the RPM, but I need to update the QEMU line before I push it to AUR.    Thanks for letting me know.
